services:
  postgres:
    image: postgres:17-alpine
    container_name: bytevault-db

    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bytevault

    volumes:
      - postgres_data:/var/lib/postgresql/data

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

  redis:
    image: redis:7-alpine
    container_name: bytevault-redis

    restart: unless-stopped

    command: redis-server --appendonly yes

    volumes:
      - redis_data:/data

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

  backend:
    build: .

    container_name: bytevault-api

    restart: unless-stopped

    ports:
      - "127.0.0.1:8080:8080"

    env_file:
      - .env

    environment:
      NOTIFICATION_FIREBASE_CREDENTIALSFILE: /firebase.json

    volumes:
      - ./firebase.json:/firebase.json:ro

    depends_on:
      - postgres
      - redis

    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/api/v1/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

volumes:
  postgres_data:
  redis_data: